
name: Run tests

on:
  push:
    branches: [copy_master]
    
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Instalar as deps do server
        uses: bahmutov/npm-install@v1
        with:
          working-diretory: server
          
      - name: Instalar as deps do web
        uses: bahmutov/npm-install@v1
        with:
          working-diretory: web
          
      - name: Component & API & UI Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          install: false
          start: npm run start:ci
          wait-on: 'http://localhost:3000/'
